# Site settings
title: (parentheticals)
email: y@lyx.io
description: > # this means to ignore newlines until "baseurl:"
  Thoughts and musings on software engineering, data science, and technology.
  Views expressed here are my own and do not represent that of my employers or
  organizations.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thirteen37.github.io" # the base hostname & protocol for your site
twitter_username: snarfnbarf
github_username:  thirteen37
timezone: Asia/Singapore
owner: Yu-Xi Lim

# Build settings
markdown: kramdown
